export type Categories =
  | 'discharge'
  | 'genderParty'
  | 'bacheloretteParty'
  | 'forMen'
  | 'forWomen'
  | 'forGirl'
  | 'forBoy'
  | 'photozones'
  | 'surpriseBox'
  | 'boxBarbie'
  | 'ballsCeil'
  | 'all'
  | '';

export type Tags =
  | 'Heart'
  | 'Star'
  | 'Circle'
  | 'ConfettiBalloon'
  | 'ChromeBalloon'
  | 'GlassBalloon'
  | 'GlassBalloonWithConfetti'
  | 'Bubbles'
  | 'Photozone'
  | 'LatexBalloons'
  | 'Figures'
  | 'Numbers'
  | 'SurpriseBox'
  | 'WalkingFigures'
  | 'BalloonBunches'
  | 'BalloonFountains'
  | 'RainBalloon';
